### ISSUE TITLE
[Bug] Error in readChar(fileName, file.info(fileName)$size) : invalid 'nchars' argument 

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/SkeletonPredictionValidationStudy#10]
After creating cohorts the following error is shown.

```
Executing SQL took 27.1 secs
Counting cohorts
Validating Models
Executing Models Using Settings
Warning: file("") only supports open = "w+" and open = "w+b": using the former
Warning: text connection used with readChar(), results may be incorrect
  Error in readChar(fileName, file.info(fileName)$size) : 
    invalid 'nchars' argument 
```

Could it be related to the problem or solution attempt in [issue#9](https://github.com/OHDSI/SkeletonPredictionValidationStudy/issues/9)

**Comment by jreps** [comment]
My guess is this is an incorrect location issue (the file it is trying to read doesn't exist) or a permission issue.  

The package should have json files for each model:
file.path(outputFolder,'inst',"models",result$models[[i]]$name,"model.json")

The code is looking in the 'models' folder for the folder named result$models[[i]]$name - do you have folders in inst/models with the name of the models you are trying to validate?  Did you build the package after creating these to make sure they exist in the library?

**Comment by lhjohn** [comment]
ATLAS uses `predictionAnalysisList.json`. I have changed it accordingly in `runModelsFromJson.R` in the develop branch.
