### ISSUE TITLE
[Bug] Incorrect syntax near '@results_database_schema'

### ISSUE THREAD

**Issue by lhjohn** [OHDSI/SkeletonPredictionValidationStudy#9]
When executing a model created from the skeleton, the following SQL error is shown.

```
DBMS:
pdw

Error:
com.microsoft.sqlserver.jdbc.SQLServerException: Parse error at line: 1, column: 13: Incorrect syntax near '@results_database_schema’.

SQL:
delete from @results_database_schema.cohort_inclusion_result where cohort_definition_id = 20613 and mode_id = 0
```

The parameter `results_database_schema` is part of the downloaded SQL files, but no value is provided for it through `SqlRender`.

**Comment by jreps** [comment]
This is an issue caused by a default setting when using webApi to extract the cohort sql - we just need to specify that no result schema is needed when running the code to create the sql.  The code in /extras needs updating with this.

**Comment by jreps** [comment]
Actually, I haven't added the code to /extras yet - I'll make the edit before I commit it
